# Generated by Django 3.1.4 on 2021-11-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
